# Generated by Django 4.2.19 on 2025-02-15 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debugsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='debugsession',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='debugsession',
            name='call_stack',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='current_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='watch_expressions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='debugsession',
            unique_together={('room', 'user')},
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='debugsession',
            name='ended_at',
        ),
    ]
