# Generated by Django 4.2.19 on 2025-02-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_debugsession_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debugsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='debugsession',
            name='room',
        ),
        migrations.RemoveField(
            model_name='debugsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rtcsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rtcsession',
            name='room',
        ),
        migrations.RemoveField(
            model_name='rtcsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userplugin',
            name='plugin',
        ),
        migrations.RemoveField(
            model_name='userplugin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='CodeReview',
        ),
        migrations.DeleteModel(
            name='DebugSession',
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
        migrations.DeleteModel(
            name='ReviewComment',
        ),
        migrations.DeleteModel(
            name='RTCSession',
        ),
        migrations.DeleteModel(
            name='UserPlugin',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
