# Generated by Django 4.2.19 on 2025-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_alter_chatmessage_room_id_fileentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileentry',
            options={'ordering': ['filename']},
        ),
        migrations.RenameField(
            model_name='fileentry',
            old_name='name',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='fileentry',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fileentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='fileentry',
            unique_together={('room', 'filename')},
        ),
    ]
